"""empty message

Revision ID: b4b51a8731fe
Revises: 
Create Date: 2023-10-02 21:23:37.013201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4b51a8731fe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charts',
    sa.Column('chart_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('chart_id')
    )
    op.create_index(op.f('ix_charts_chart_id'), 'charts', ['chart_id'], unique=False)
    op.create_table('demo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('total_enrollment', sa.String(), nullable=True),
    sa.Column('grade_k', sa.String(), nullable=True),
    sa.Column('grade_1', sa.String(), nullable=True),
    sa.Column('grade_2', sa.String(), nullable=True),
    sa.Column('grade_3', sa.String(), nullable=True),
    sa.Column('grade_4', sa.String(), nullable=True),
    sa.Column('grade_5', sa.String(), nullable=True),
    sa.Column('grade_6', sa.String(), nullable=True),
    sa.Column('grade_7', sa.String(), nullable=True),
    sa.Column('grade_8', sa.String(), nullable=True),
    sa.Column('female', sa.String(), nullable=True),
    sa.Column('female_percent', sa.String(), nullable=True),
    sa.Column('male', sa.String(), nullable=True),
    sa.Column('male_percent', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demo_id'), 'demo', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_demo_id'), table_name='demo')
    op.drop_table('demo')
    op.drop_index(op.f('ix_charts_chart_id'), table_name='charts')
    op.drop_table('charts')
    # ### end Alembic commands ###
